### PR TITLE
Placeholder for discussion

### PR DESCRIPTION
**Pull request by M1thrandir**
So... months ago I forked your repo because it was an awesome start at adding some flavor to Discourse and I wanted to make changes without affecting your branch/without waiting for code review and approval. Now it's been a little while since I touched it and looked at the compare out of curiosity; which looks like you haven't changed a great deal (pending the open pull requests) since I forked the branch.

If any of you don't mind taking the time to import it into Discourse and share feedback, I would appreciate it. The only noticeable change I made to your styling was the size of the create fab from a larger size to the standard 56 in the material guidelines and a couple swaps of $tertiary for $quaternary (I included two color schemes with my GitHub username for you to compare). Otherwise, any changes (not additions) facilitate the same look and feel, just in a different way or higher in the chain in order to use the inheritance. Also, please ignore the number of commits and lack of descriptions; I originally just edited the scss directly in GitHub for speed while playing around with how I wanted things to look. Though I didn't originally fork the branch to share, so let me know if the comments aren't thorough enough.

Ultimately, I don't mind whether you would like to merge any of my changes, but I wanted to share the additions just in case. Also, I wouldn't mind contributing in the future as Discourse evolves if you guys need a hand.

Thanks

### CODE REVIEW

**Comment by jomaxro** [comment]
@M1thrandir, thanks for all the changes. Would you mind breaking this up into some smaller PRs so we can more easily see what you've changed? For example, one PR for the changes to the FAB. One PR for changes to the topic view. One PR for changes to the topic list view. etc.

**Comment by M1thrandir** [comment]
Yeah, I can do that. It might take me a bit to get to it though, so in the mean time let me know if there's anything that stands out and we can get it changed while I'm piecing it out.

**Comment by jomaxro** [comment]
I can absolutely take a look at this, but I've got a lot on my plate this week. I may not be able to take a good look until next week.

**Comment by ZogStriP** [comment]
Also @M1thrandir, one thing that helps a lot is posting before/after screenshots ;)

**Comment by rewphus** [comment]
I'll try to take a look at this soon as well.  I finally got my dev instance up and running, so I just have to find the time to comb through this now.  Thanks for the contribution!

**Comment by M1thrandir** [comment]
Ignore that last commit. I was hoping that I could split out the scss into multiple files to make maintenance better, but it looks like the code using custom theme files is picking them out by name prior to compiling to css. I've branched your repo directly to break this up and reduce conflicts; would you prefer one pull at a time or shotgun it and merge in arbitrary order?

**Comment by M1thrandir** [comment]
Just chiming in since I haven't heard back. Whether one or several of you guys are reviewing, would you like to focus on one pull at a time or do you want them a few or all at once so that some can get merged if others get changes made?

Also, after playing with split up files on that last commit, I took a look at the source and it looks like external links would still work in the specific scss files for custom themes. Has anyone tried importing the material library from google and extending classes so that the styles don't have to be recreated? It seems like with scss/sass we should be able to consolidate these files a great deal. I was also considering creating file specific variables as a set of standards for material styling across the theme.

Thoughts?

**Comment by jomaxro** [comment]
Hi @M1thrandir, my apologies for not responding, I've been travelling. I'd say go ahead and shotgun all the pulls. As you mentioned there may be different people reviewing them so having them all available would be helpful.

**Comment by SamSaffron** [comment]
sadly we cant sit on this big PR for years.

@M1thrandir  if you make small PRs with before and after screenshots we can assess and merge in very short order.

**Pull request closed without merging**
