### PR TITLE
Update desktop.scss

### PR DESCRIPTION
**Pull request by jamesn81**
Recent changes to class names require .latest-topic-list to be used.

### CODE REVIEW

**Comment by jomaxro** [comment]
Seeing as the CSS rules for `.latest-topic-list` are the same as `.category-list, .topic-list:not(.categories)`, any reason why you didn't add `.latest-topic-list` to the existing selector?

**Comment by jamesn81** [comment]
Yes - that one you mention refers to the 'latest' only view, whereas the one I've pasted only controls the right hand view of the categories and latest view.

Does that make sense?

**Comment by jomaxro** [comment]
It does, but at the moment there seems to be extra rule duplication. Here's what would be in the file after the PR:

```
 //add shadow behind the list of topics, but not categories
 .category-list, .topic-list:not(.categories){
   -webkit-box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
   -moz-box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
   box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
   background-color: lighten($secondary, 10%);
    border-collapse: collapse;
  }
  
 //shadow behind list of topics on right hand side when in cateogry list view
 .latest-topic-list {
   -webkit-box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
   -moz-box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
   box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
   background-color: lighten($secondary, 10%);
   border-collapse: collapse;
 }
```

This entire section is the same, so it's there twice:
```
   -webkit-box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
   -moz-box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
   box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
   background-color: lighten($secondary, 10%);
   border-collapse: collapse;
```

What I'm suggesting is to do the following:
```
//add shadow behind the list of topics, but not categories
//shadow behind list of topics on right hand side when in cateogry list view
.category-list, .topic-list:not(.categories), .latest-topic-list{
  -webkit-box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
  -moz-box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
  box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
  background-color: lighten($secondary, 10%);
  border-collapse: collapse;
  }
```

**Comment by jomaxro** [comment]
Feel free to adjust the comments as you see fit. I simply copied and pasted one above the other for my example 😄.

**Pull request merged**
